#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "driver/gpio.h"
#include "sdkconfig.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef CONFIG_LISTENER_BOARD_PROFILE_V2_N16R8
#define CONFIG_LISTENER_BOARD_PROFILE_V2_N16R8 1
#endif

#if !CONFIG_LISTENER_BOARD_PROFILE_V2_N16R8
#error "Only the Voice Keyboard V2/N16R8 board profile is supported in this build baseline."
#endif

#define BOARD_PINS_PROFILE_ID        "voice-keyboard-v2-n16r8"
#define BOARD_PINS_MODULE            "ESP32-S3-WROOM-1-N16R8"
#define BOARD_PINS_FLASH_SIZE_MB     (16)
#define BOARD_PINS_PSRAM_SIZE_MB     (8)
#define BOARD_PINS_PSRAM_MODE        "octal"

#define BOARD_PINS_I2S_PORT          (0)
#define BOARD_PINS_I2S_MCLK_IO       (GPIO_NUM_NC)
#define BOARD_PINS_MIC_CLK_IO        (GPIO_NUM_48)
#define BOARD_PINS_MIC_DOUT_IO       (GPIO_NUM_47)
#define BOARD_PINS_I2S_BCLK_IO       BOARD_PINS_MIC_CLK_IO
#define BOARD_PINS_I2S_WS_IO         (GPIO_NUM_NC)
#define BOARD_PINS_I2S_DIN_IO        BOARD_PINS_MIC_DOUT_IO
#define BOARD_PINS_I2S_DOUT_IO       (GPIO_NUM_NC)

#define BOARD_PINS_KEY1_IO           (GPIO_NUM_38)
#define BOARD_PINS_KEY2_IO           (GPIO_NUM_39)
#define BOARD_PINS_KEY3_IO           (GPIO_NUM_40)
#define BOARD_PINS_KEY4_IO           (GPIO_NUM_41)

#define BOARD_PINS_EC11_A_IO         (GPIO_NUM_42)
#define BOARD_PINS_EC11_B_IO         (GPIO_NUM_2)
#define BOARD_PINS_EC11_C_IO         (GPIO_NUM_NC)
#define BOARD_PINS_EC11_KEY_IO       (GPIO_NUM_11)

#define BOARD_PINS_BAT_CHG_IO        (GPIO_NUM_14)
#define BOARD_PINS_BAT_STD_IO        (GPIO_NUM_21)
#define BOARD_PINS_BAT_V_ADC_IO      (GPIO_NUM_8)
#define BOARD_PINS_USB_DET_IO        (GPIO_NUM_7)
#define BOARD_PINS_USB_DP_IO         (GPIO_NUM_20)
#define BOARD_PINS_USB_DN_IO         (GPIO_NUM_19)

#define BOARD_PINS_RGB_STATUS_IO     (GPIO_NUM_1)
#define BOARD_PINS_RGB_KEY_IO        (GPIO_NUM_13)
#define BOARD_PINS_RGB_EDGE_IO       (GPIO_NUM_4)

#define BOARD_PINS_PWR_HOLD_IO       (GPIO_NUM_46)
#define BOARD_PINS_TPS63020_I_ADC_IO (GPIO_NUM_10)
#define BOARD_PINS_SY7088_I_ADC_IO   (GPIO_NUM_9)

#define BOARD_PINS_N16R8_MSPI_GPIO35 (GPIO_NUM_35)
#define BOARD_PINS_N16R8_MSPI_GPIO36 (GPIO_NUM_36)
#define BOARD_PINS_N16R8_MSPI_GPIO37 (GPIO_NUM_37)

#define BOARD_PINS_IS_N16R8_MSPI_RESERVED(gpio) \
    ((gpio) == GPIO_NUM_35 || (gpio) == GPIO_NUM_36 || (gpio) == GPIO_NUM_37)

#define BOARD_PINS_ASSERT_NOT_N16R8_MSPI(name, gpio) \
    typedef char board_pins_##name##_must_not_use_n16r8_mspi[(BOARD_PINS_IS_N16R8_MSPI_RESERVED(gpio)) ? -1 : 1]

BOARD_PINS_ASSERT_NOT_N16R8_MSPI(key1, BOARD_PINS_KEY1_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(key2, BOARD_PINS_KEY2_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(key3, BOARD_PINS_KEY3_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(key4, BOARD_PINS_KEY4_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(ec11_a, BOARD_PINS_EC11_A_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(ec11_b, BOARD_PINS_EC11_B_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(ec11_c, BOARD_PINS_EC11_C_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(ec11_key, BOARD_PINS_EC11_KEY_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(mic_clk, BOARD_PINS_MIC_CLK_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(mic_dout, BOARD_PINS_MIC_DOUT_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(bat_chg, BOARD_PINS_BAT_CHG_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(bat_std, BOARD_PINS_BAT_STD_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(bat_v_adc, BOARD_PINS_BAT_V_ADC_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(usb_det, BOARD_PINS_USB_DET_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(usb_dp, BOARD_PINS_USB_DP_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(usb_dn, BOARD_PINS_USB_DN_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(rgb_status, BOARD_PINS_RGB_STATUS_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(rgb_key, BOARD_PINS_RGB_KEY_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(rgb_edge, BOARD_PINS_RGB_EDGE_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(pwr_hold, BOARD_PINS_PWR_HOLD_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(tps63020_i_adc, BOARD_PINS_TPS63020_I_ADC_IO);
BOARD_PINS_ASSERT_NOT_N16R8_MSPI(sy7088_i_adc, BOARD_PINS_SY7088_I_ADC_IO);

#ifdef __cplusplus
}
#endif

#endif
