param(
    [string]$Port,
    [string]$Target = "esp32s3",
    [string]$BuildDir = $env:LISTENER_IDF_BUILD_DIR,
    [int]$ShutdownMs = 60000,
    [switch]$NoBuild,
    [switch]$NoFlash
)

$ErrorActionPreference = "Stop"

if ($ShutdownMs -lt 10000) {
    throw "ShutdownMs must be at least 10000 to avoid accidental instant power-off during validation."
}
if ($NoBuild -and $NoFlash) {
    throw "Specify at most one of -NoBuild and -NoFlash."
}
if (-not $NoFlash -and [string]::IsNullOrWhiteSpace($Port)) {
    throw "Port is required unless -NoFlash is specified."
}

$projectRoot = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot "idf_env.ps1") -Target $Target

function Get-ShortBuildDir {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    if (-not [string]::IsNullOrWhiteSpace($BuildDir)) {
        return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($BuildDir)
    }

    if ($ProjectRoot.Length -lt 80) {
        return Join-Path $ProjectRoot "build"
    }

    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($ProjectRoot.ToLowerInvariant())
        $hashBytes = $sha1.ComputeHash($bytes)
        $hash = -join ($hashBytes[0..5] | ForEach-Object { $_.ToString("x2") })
    } finally {
        $sha1.Dispose()
    }
    return Join-Path ([System.IO.Path]::GetTempPath()) "listener-idf-build-$hash"
}

function Invoke-LoggedCommand {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][string]$LogPath,
        [Parameter(Mandatory = $true)][scriptblock]$Body
    )

    Write-Output "== $Name =="
    $global:LASTEXITCODE = 0
    & $Body *>&1 | Tee-Object -FilePath $LogPath
    if ($LASTEXITCODE -ne 0) {
        throw "$Name failed with exit code $LASTEXITCODE. See $LogPath"
    }
}

function Set-HardwareShutdownConfig {
    param(
        [Parameter(Mandatory = $true)][string]$SdkconfigPath,
        [Parameter(Mandatory = $true)][int]$ValueMs
    )

    $line = "CONFIG_POWER_MANAGER_HARDWARE_SHUTDOWN_MS=$ValueMs"
    $text = Get-Content -LiteralPath $SdkconfigPath -Raw
    if ($text -match '(?m)^CONFIG_POWER_MANAGER_HARDWARE_SHUTDOWN_MS=\d+\r?$') {
        $text = $text -replace '(?m)^CONFIG_POWER_MANAGER_HARDWARE_SHUTDOWN_MS=\d+\r?$', $line
    } else {
        $text = $text.TrimEnd() + [Environment]::NewLine + $line + [Environment]::NewLine
    }
    Set-Content -LiteralPath $SdkconfigPath -Value $text -Encoding UTF8
}

$buildDirResolved = Get-ShortBuildDir -ProjectRoot $projectRoot
$artifactDir = Join-Path $projectRoot "tests\artifacts\firmware_power_off_1_2"
New-Item -ItemType Directory -Path $artifactDir -Force | Out-Null
$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$buildLog = Join-Path $artifactDir "power_off_validation_build_${ShutdownMs}ms_$stamp.log"
$flashLog = Join-Path $artifactDir "power_off_validation_flash_${ShutdownMs}ms_$stamp.log"
$manifestPath = Join-Path $artifactDir "power_off_validation_manifest_${ShutdownMs}ms_$stamp.json"
$sdkconfigPath = Join-Path $projectRoot "sdkconfig"
$backupPath = $null
$sdkconfigExisted = Test-Path -LiteralPath $sdkconfigPath
$sdkconfigRestored = $false

try {
    if (-not $NoBuild) {
        if (-not $sdkconfigExisted) {
            Invoke-LoggedCommand -Name "idf set-target $Target" -LogPath $buildLog -Body {
                & pwsh -NoProfile -File (Join-Path $PSScriptRoot "idf.ps1") -B $buildDirResolved set-target $Target
            }
            $sdkconfigExisted = Test-Path -LiteralPath $sdkconfigPath
        }
        if (-not $sdkconfigExisted) {
            throw "sdkconfig was not generated by tools\idf.ps1 set-target."
        }

        $backupPath = Join-Path ([System.IO.Path]::GetTempPath()) ("listener-power-off-sdkconfig-{0}.bak" -f $stamp)
        Copy-Item -LiteralPath $sdkconfigPath -Destination $backupPath -Force
        Set-HardwareShutdownConfig -SdkconfigPath $sdkconfigPath -ValueMs $ShutdownMs

        Invoke-LoggedCommand -Name "build power-off validation firmware (${ShutdownMs}ms)" -LogPath $buildLog -Body {
            & pwsh -NoProfile -File (Join-Path $PSScriptRoot "idf.ps1") -B $buildDirResolved build
        }

        $sdkconfigHeader = Join-Path $buildDirResolved "config\sdkconfig.h"
        if (-not (Test-Path -LiteralPath $sdkconfigHeader -PathType Leaf)) {
            throw "Build did not produce $sdkconfigHeader"
        }
        $headerText = Get-Content -LiteralPath $sdkconfigHeader -Raw
        if ($headerText -notmatch "#define\s+CONFIG_POWER_MANAGER_HARDWARE_SHUTDOWN_MS\s+$ShutdownMs\b") {
            throw "Build config did not contain CONFIG_POWER_MANAGER_HARDWARE_SHUTDOWN_MS=$ShutdownMs"
        }
    }

    if (-not $NoFlash) {
        Invoke-LoggedCommand -Name "flash power-off validation firmware (${ShutdownMs}ms)" -LogPath $flashLog -Body {
            & pwsh -NoProfile -File (Join-Path $PSScriptRoot "idf.ps1") -B $buildDirResolved -p $Port flash
        }
    }
} finally {
    if ($backupPath -and (Test-Path -LiteralPath $backupPath -PathType Leaf)) {
        Copy-Item -LiteralPath $backupPath -Destination $sdkconfigPath -Force
        Remove-Item -LiteralPath $backupPath -Force
        $sdkconfigRestored = $true
    }
}

$commit = (& git -C $projectRoot rev-parse HEAD).Trim()
$branch = (& git -C $projectRoot branch --show-current).Trim()
$manifest = [ordered]@{
    schema_version = 1
    generated_at = (Get-Date).ToString("o")
    repo_root = $projectRoot
    branch = $branch
    commit = $commit
    target = $Target
    port = if ($Port) { $Port } else { $null }
    build_dir = $buildDirResolved
    shutdown_ms = $ShutdownMs
    no_build = [bool]$NoBuild
    no_flash = [bool]$NoFlash
    sdkconfig_restored = [bool]$sdkconfigRestored
    build_log = if ((Test-Path -LiteralPath $buildLog -PathType Leaf)) { $buildLog } else { $null }
    flash_log = if ((Test-Path -LiteralPath $flashLog -PathType Leaf)) { $flashLog } else { $null }
}
$manifest | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

Write-Output "POWER_OFF_VALIDATION_MANIFEST: $manifestPath"
Write-Output "POWER_OFF_VALIDATION_BUILD_DIR: $buildDirResolved"
Write-Output "POWER_OFF_VALIDATION_SHUTDOWN_MS: $ShutdownMs"
